### ISSUE TITLE
Link conference paper in ep. 1

### ISSUE THREAD

**Issue by apandas** [UCSBCarpentry/Reproducible-Publications-with-RStudio#12] opened 2022-01-21 01:05 UTC

**Comment by ilessing** [comment] 2022-02-18 20:18
@apandas Can you take a look and see if the conference paper is linked as needed now?
There are links to a couple of papers at the [bottom of Episode 1](https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio/01-introduction/index.html#some-real-world-applications). 

See screenshot: 
![issue12-Screen Shot 2022-02-18 at 12 10 33 PM](https://user-images.githubusercontent.com/275899/154755387-61099a52-4710-4a04-92b9-a42acbec9375.png)


But I'm not sure if that is what you intended for this GitHub issue.

Please either approve the linking by closing this issue or indicate where the link needs to be added and to what conference paper.

thanks!

**Comment by rcurty** [comment] 2022-02-23 05:47
replaced example, fixed language and updated links

**Closed by rcurty** 2022-02-23 05:47 UTC
