### ISSUE TITLE
ep. 6 visual editor button clarification - add screen shot

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/Reproducible-Publications-with-RStudio#44] opened 2022-02-18 00:46 UTC
I’m not sure how intuitive it is that the ‘A’ button is a compass. Might want to include a picture of the bar with the symbol you’re referring to circle

**Comment by ilessing** [comment] 2022-02-22 18:17
I think this issue is a duplicate of #30 and can probably be closed.

@rcurty if you agree please close this issue.

**Closed** 2022-02-23 01:14 UTC
